# Site settings
title: Chalmers Kristna Grupp
email: info@ckg.nu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "new.ckg.nu" # the base hostname & protocol for your site

twitter_username:
github_username: lindhe

# Build settings
markdown: kramdown
